apiVersion: v1
kind: Service
metadata:
  name: jonas-portfolio-prod
  namespace: portfolio-prod
spec:
  type: NodePort
  selector:
    app: my-portfolio
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31500