name: STAGE -> Docker Build & Push

on:
  push:
    branches: [ "stage" ]
  merge_group:
    branches: [ "stage" ]

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: jonasbe25/my-portfolio
          tags: stage
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest


      - name: Download kubeconfig
        run: |
          mkdir $HOME/.kube
          echo '${{ secrets.KUBECONFIG }}' >> $HOME/.kube/config


      - name: Deploy to cluster
        run: |
          kubectl apply -f kubernetes/deployment-stage.yaml
          kubectl rollout restart deployment jonas-portfolio-stage